plugins:
  - name: solidity
  - name: vyper
  - name: hardhat
  - name: infura
  - name: tokens
  - name: etherscan

# require OpenZepplin Contracts
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.1
  - name: openzeppelin-upgradeable
    github: OpenZeppelin/openzeppelin-contracts-upgradeable
    version: 4.7.1
  - name: vault
    github: pandadefi/yearn-vaults
    branch: release_0.4.4

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.7.1"
    - "@openzeppelin-upgradeable/contracts=openzeppelin-upgradeable/v4.7.1"

default_ecosystem: ethereum

hardhat:
  port: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura

ethereum:
  default_network: local
  local:
    default_provider: hardhat
