name: Test

on:
  push:
    branches:
    - master
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ApeWorX/github-action@v1

    - name: Compile contracts
      run: ape compile --size

    # Needed to use hardhat
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install hardhat
      run: npm install hardhat

    - name: Run tests
      env:
          WEB3_INFURA_PROJECT_ID: b7821200399e4be2b4e5dbdf06fbe85b        
      run: ape test -s
      timeout-minutes: 10
