name: Test

on:
  push:
    branches:
    - master
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ApeWorX/github-action@v1
      with:
        python-version: 3.9

    - name: install foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        export PATH="$PATH:/home/runner/.foundry/bin"
        foundryup

    - name: install vyper # should be removed onced 0.3.4 is released.
      run: pip install git+https://github.com/vyperlang/vyper
  
    - name: install plugins
      run: ape plugins install .

    - name: Compile contracts
      run: ape compile --size
    - name: Run tests
      run: |
        export PATH="$PATH:/home/runner/.foundry/bin"
        ape test -s
      timeout-minutes: 10
